# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlggroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgGroup(object):
    def setupUi(self, DlgGroup):
        DlgGroup.setObjectName("DlgGroup")
        DlgGroup.resize(320, 90)
        DlgGroup.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(DlgGroup)
        self.gridLayout.setContentsMargins(6, 2, 6, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(DlgGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leName = QtWidgets.QLineEdit(DlgGroup)
        self.leName.setObjectName("leName")
        self.gridLayout.addWidget(self.leName, 0, 1, 1, 1)
        self.chTopLevel = QtWidgets.QCheckBox(DlgGroup)
        self.chTopLevel.setObjectName("chTopLevel")
        self.gridLayout.addWidget(self.chTopLevel, 1, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgGroup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(DlgGroup)
        self.buttonBox.accepted.connect(DlgGroup.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgGroup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgGroup)

    def retranslateUi(self, DlgGroup):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DlgGroup", "Name"))
        self.chTopLevel.setText(_translate("DlgGroup", "Top level folder"))
