# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgfood.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgFood(object):
    def setupUi(self, DlgFood):
        DlgFood.setObjectName("DlgFood")
        DlgFood.resize(295, 234)
        DlgFood.setMinimumSize(QtCore.QSize(295, 234))
        DlgFood.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(DlgFood)
        self.gridLayout.setContentsMargins(-1, -1, -1, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.leName = QtWidgets.QLineEdit(DlgFood)
        self.leName.setObjectName("leName")
        self.gridLayout.addWidget(self.leName, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(DlgFood)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(DlgFood)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.sbCalories = QtWidgets.QDoubleSpinBox(DlgFood)
        self.sbCalories.setMaximum(999.99)
        self.sbCalories.setObjectName("sbCalories")
        self.gridLayout.addWidget(self.sbCalories, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(DlgFood)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 34))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(DlgFood)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.sbProt = QtWidgets.QDoubleSpinBox(DlgFood)
        self.sbProt.setObjectName("sbProt")
        self.gridLayout.addWidget(self.sbProt, 3, 2, 1, 1)
        self.sbFat = QtWidgets.QDoubleSpinBox(DlgFood)
        self.sbFat.setObjectName("sbFat")
        self.gridLayout.addWidget(self.sbFat, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(DlgFood)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(DlgFood)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.sbCarbo = QtWidgets.QDoubleSpinBox(DlgFood)
        self.sbCarbo.setObjectName("sbCarbo")
        self.gridLayout.addWidget(self.sbCarbo, 5, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgFood)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 3)

        self.retranslateUi(DlgFood)
        self.buttonBox.accepted.connect(DlgFood.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgFood.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgFood)

    def retranslateUi(self, DlgFood):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DlgFood", "Product (dish) name"))
        self.label_2.setText(_translate("DlgFood", "Caloric content of 100 g, kcal"))
        self.label_3.setText(_translate("DlgFood", "<html><head/><body><p><span style=\" font-weight:600; color:#934900;\">Content in 100 g of the product (dish):</span></p></body></html>"))
        self.label_5.setText(_translate("DlgFood", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">fats, g</span></p></body></html>"))
        self.label_4.setText(_translate("DlgFood", "<html><head/><body><p><span style=\" font-weight:600; color:#008200;\">proteins, g</span></p></body></html>"))
        self.label_6.setText(_translate("DlgFood", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">carbohydrates, g</span></p></body></html>"))
