# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgday.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgDay(object):
    def setupUi(self, DlgDay):
        DlgDay.setObjectName("DlgDay")
        DlgDay.resize(210, 200)
        DlgDay.setWindowTitle("")
        self.buttonBox = QtWidgets.QDialogButtonBox(DlgDay)
        self.buttonBox.setGeometry(QtCore.QRect(30, 170, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.dateEdit = QtWidgets.QDateEdit(DlgDay)
        self.dateEdit.setGeometry(QtCore.QRect(80, 20, 90, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(DlgDay)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.sbWeight = QtWidgets.QDoubleSpinBox(DlgDay)
        self.sbWeight.setGeometry(QtCore.QRect(80, 50, 60, 22))
        self.sbWeight.setDecimals(1)
        self.sbWeight.setMinimum(0.0)
        self.sbWeight.setMaximum(300.0)
        self.sbWeight.setProperty("value", 60.0)
        self.sbWeight.setObjectName("sbWeight")
        self.label_2 = QtWidgets.QLabel(DlgDay)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.sbWaist = QtWidgets.QSpinBox(DlgDay)
        self.sbWaist.setGeometry(QtCore.QRect(80, 80, 60, 22))
        self.sbWaist.setMaximum(250)
        self.sbWaist.setObjectName("sbWaist")
        self.label_3 = QtWidgets.QLabel(DlgDay)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DlgDay)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.sbHips = QtWidgets.QSpinBox(DlgDay)
        self.sbHips.setGeometry(QtCore.QRect(80, 110, 60, 22))
        self.sbHips.setMaximum(250)
        self.sbHips.setObjectName("sbHips")
        self.lbUser = QtWidgets.QLabel(DlgDay)
        self.lbUser.setGeometry(QtCore.QRect(20, 0, 177, 13))
        self.lbUser.setAlignment(QtCore.Qt.AlignCenter)
        self.lbUser.setObjectName("lbUser")

        self.retranslateUi(DlgDay)
        self.buttonBox.accepted.connect(DlgDay.accept) # type: ignore
        self.buttonBox.rejected.connect(DlgDay.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DlgDay)

    def retranslateUi(self, DlgDay):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("DlgDay", "Date"))
        self.label_2.setText(_translate("DlgDay", "Weight"))
        self.label_3.setText(_translate("DlgDay", "Waist"))
        self.label_4.setText(_translate("DlgDay", "Hips"))
        self.lbUser.setText(_translate("DlgDay", "Guest"))
