PRAGMA foreign_keys = off;
BEGIN TRANSACTION;
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (1, 0, 1, '1-е блюда', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (2, 0, 1, '2-е блюда', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (3, 0, 1, 'блюда из мяса', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (4, 0, 1, 'блюда из рыбы и морепродуктов', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (5, 0, 1, 'бутерброды', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (6, 0, 1, 'выпечка', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (7, 0, 1, 'гарниры', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (8, 0, 1, 'жиры, соусы', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (9, 0, 1, 'колбасы, мясные деликатесы', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (10, 0, 1, 'кондитерские изделия', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (11, 0, 1, 'молочные продукты', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (12, 0, 1, 'напитки', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (13, 0, 1, 'напитки спиртные', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (14, 0, 1, 'овощи', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (15, 0, 1, 'орехи, семечки', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (16, 0, 1, 'салаты', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (17, 0, 1, 'сахар, мед, варенье', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (18, 0, 1, 'соленья, маринады, овощные консервы', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (19, 0, 1, 'фрукты и ягоды', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (20, 0, 1, 'хлебобулочные изделия', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (21, 0, 1, 'хлопья, отруби', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (22, 0, 1, 'яйца', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (23, 1, 0, 'суп с фрикадельками', 79, 4, 4.6, 5.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (24, 11, 1, 'молоко, кисломолочные продукты', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (25, 11, 1, 'сыры', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (26, 11, 1, 'твороги', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (27, 26, 0, 'творог 0%', 79, 16, 0.3, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (28, 24, 0, 'молоко 3,2%', 59, 2.8, 3.2, 4.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (29, 20, 0, 'хлеб бородинский', 208, 6.4, 1.2, 41.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (30, 25, 0, 'сыр голландский', 352, 26, 28, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (31, 17, 0, 'сахар', 387, 0, 0, 99);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (32, 12, 1, 'чай, кофе, компоты', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (34, 32, 0, 'кофе', 2, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (35, 20, 0, 'хлебцы ржаные', 323, 12, 3, 62);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (36, 13, 0, 'коньяк', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (37, 13, 0, 'водка', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (38, 14, 0, 'огурцы', 14, 0, 0.8, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (39, 14, 0, 'помидоры', 23, 1.1, 0.2, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (40, 3, 0, 'котлета из индеки', 183, 16.3, 9.9, 7.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (41, 7, 0, 'гречка на воде', 103, 4.2, 1.1, 20.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (42, 19, 0, 'яблоко', 37, 0.2, 0.3, 8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (43, 19, 0, 'арбуз', 27, 0.6, 0.1, 5.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (44, 4, 0, 'лосось запеченый', 204, 16.2, 14.8, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (45, 7, 0, 'картофельное пюре с молоком и маслом', 104, 2.1, 5.6, 11.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (46, 32, 0, 'чай', 1, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (47, 19, 0, 'груша', 42, 0.4, 0.3, 9.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (48, 1, 0, 'суп куриный с лапшой', 85, 4.2, 4, 8.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (49, 6, 0, 'запеканка творожная', 220, 13.1, 12, 14.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (50, 3, 0, 'гуляш из свинины', 164, 11, 8.4, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (51, 2, 0, 'баклажаны с помидорами жареные', 91, 1.9, 5.5, 9.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (52, 2, 0, 'пельмени', 275, 11.9, 12.4, 29);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (53, 22, 0, 'яйцо куриное', 157, 12.7, 11.5, 0.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (54, 9, 0, 'сервелат', 360, 28.2, 27.5, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (55, 3, 0, 'курица отварная', 137, 29.8, 1.8, 0.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (56, 10, 0, 'шоколад', 544, 5.4, 35.3, 56.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (57, 8, 0, 'масло сливочное 82%', 748, 0.5, 82.5, 0.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (58, 7, 0, 'рис на воде', 95, 1.7, 0.4, 20.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (59, 9, 0, 'сосиска докторская', 250, 11.3, 22, 1.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (60, 18, 0, 'имбирь маринованный', 51, 0.2, 0.3, 12.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (61, 24, 0, 'сметана 20%', 204, 2.5, 20, 3.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (62, 9, 0, 'колбаса докторская', 255, 30.1, 21.7, 1.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (63, 19, 0, 'нектарин', 48, 0.9, 0.2, 11.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (64, 20, 0, 'батон подмосковный', 261, 7.5, 2.6, 50.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (65, 25, 0, 'сыр адыгейский', 264, 19.8, 19.8, 1.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (66, 10, 0, 'мармелад', 306, 0.4, 0, 76);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (67, 4, 0, 'крабовые палочки', 95, 8, 0.5, 15);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (68, 4, 0, 'окунь морской', 120, 19, 4, 0.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (69, 20, 0, 'лаваш', 236, 7.9, 1, 47.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (70, 2, 0, 'плов', 239, 18.2, 16.1, 7.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (71, 10, 0, 'шербет', 368, 5.7, 13.9, 55.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (72, 20, 0, 'хлеб ржаной', 165, 6.6, 1.2, 34.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (73, 4, 0, 'минтай жареный', 137, 14.7, 8.7, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (74, 18, 0, 'огурцы маринованные', 16, 2.8, 0, 1.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (75, 20, 0, 'хлеб чусовской', 212, 7.8, 1.2, 46.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (76, 14, 0, 'морковь вареная', 25, 0.8, 0.3, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (77, 18, 0, 'морковь по корейски', 139, 1.2, 11, 8.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (78, 10, 0, 'конфеты шоколадные', 500, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (79, 10, 0, 'зефир', 318, 0.8, 0.1, 76);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (80, 6, 0, 'пирог с брусникой (вишней)', 206, 3, 8.7, 38);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (81, 8, 0, 'соус томатный', 54, 0.8, 0, 12.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (82, 2, 0, 'рагу овощное', 91, 1.9, 4.5, 10.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (83, 20, 0, 'хлеб ржаной таежный', 202, 6.5, 1.3, 43.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (84, 2, 0, 'грузди жареные', 62, 2.1, 5.2, 2.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (85, 9, 0, 'шейка варено-копченая', 319, 10, 31, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (86, 6, 0, 'расстегай (пирог) с рыбой', 227, 11, 9, 26);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (87, 18, 0, 'огурцы соленые', 13, 0.6, 0.1, 1.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (88, 10, 0, 'зефир в шоколаде', 396, 2.2, 12.3, 68.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (89, 24, 0, 'йогурт', 80, 3.4, 2.5, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (90, 19, 0, 'виноград', 65, 0.6, 0.2, 16.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (91, 2, 0, 'рыжики жареные', 85, 3.7, 5.7, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (92, 7, 0, 'картофель отварной', 82, 2, 0.4, 16.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (93, 9, 0, 'холодец', 196, 15.2, 13.8, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (94, 20, 0, 'хлеб крестьянский', 236, 7.7, 1, 47.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (95, 10, 0, 'шоколад 70%', 549, 9.1, 39, 36);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (96, 10, 0, 'пряники', 348, 4.7, 4.7, 69.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (97, 3, 0, 'свинина тушеная', 259, 12, 22, 2.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (98, 7, 0, 'картофель тушеный', 101, 2.8, 4.1, 12.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (99, 11, 1, 'мороженое', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (100, 99, 0, 'пломбир', 227, 3.2, 15, 20.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (101, 10, 0, 'рахат-лукум', 316, 0.8, 0.7, 79.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (102, 25, 0, 'сырный продукт моцарелла', 210, 12, 30, 7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (103, 7, 0, 'макароны отварные', 111, 3, 0.4, 23);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (104, 9, 0, 'карбонад', 230, 14, 20, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (105, 19, 0, 'дыня', 33, 0.6, 0.3, 7.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (106, 14, 0, 'листья салата', 12, 1.2, 0.3, 1.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (107, 3, 0, 'индейка тушеная', 127, 16.8, 5.66, 2.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (108, 6, 0, 'ватрушка с творогом', 238, 8.9, 8.2, 33.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (109, 2, 0, 'запеканка из кабачков', 63, 5.8, 2.6, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (110, 24, 0, 'йогурт талицкий', 110, 2.8, 9, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (111, 2, 0, 'омлет', 184, 9.6, 15.4, 1.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (112, 6, 0, 'блины', 233, 6.1, 12.3, 26);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (113, 3, 0, 'печень говяжья тушеная', 132, 14.7, 4.9, 7.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (114, 19, 0, 'инжир', 49, 0.7, 0.2, 13.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (115, 19, 0, 'абрикос', 41, 0.9, 0.1, 10.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (116, 19, 0, 'слива', 42, 0.8, 0.3, 9.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (117, 14, 0, 'редис', 21, 1.2, 0.1, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (118, 6, 0, 'пирог с капустой', 235, 6.3, 8.9, 35.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (119, 6, 0, 'манник', 237, 6.8, 3.1, 46.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (120, 2, 0, 'кукуруза вареная', 123, 4.1, 2.3, 22.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (121, 14, 0, 'лук зеленый', 19, 1.3, 0, 3.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (122, 8, 0, 'масло подсолнечное', 889, 0, 99.9, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (123, 1, 0, 'бульон куриный', 15, 2, 0.5, 0.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (124, 6, 0, 'пирог с луком и яйцом', 263, 11.2, 9.3, 35.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (125, 6, 0, 'пирог с яблоком', 207, 4.5, 5.2, 35.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (126, 6, 0, 'булочка с повидлом', 295, 4.4, 8.7, 51.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (127, 1, 0, 'борщ мясной', 85, 4.8, 4.1, 4.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (128, 3, 0, 'свинина отварная', 131, 30.7, 0.9, 0.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (129, 3, 0, 'куриные голени тушеные', 175, 19, 9.5, 0.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (130, 2, 0, 'грибы жареные', 57, 3.7, 4, 2.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (131, 2, 0, 'голубцы', 181, 7.1, 12.2, 11.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (132, 7, 0, 'перловка на воде', 109, 3.1, 0.4, 22.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (133, 19, 0, 'персик', 45, 0.9, 0.1, 9.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (134, 2, 0, 'свинина тушеная с картофелем', 150, 6.4, 10.6, 8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (135, 2, 0, 'вареники с вишней', 184, 4.4, 3.2, 36);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (136, 15, 0, 'орехи грецкие', 654, 15, 65, 7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (137, 24, 0, 'ряженка 2,5%', 52, 2.9, 2.5, 4.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (138, 17, 0, 'мед', 309, 0.8, 0, 81.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (139, 24, 0, 'простокваша', 64, 2.8, 3.5, 4.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (140, 9, 0, 'корейка', 280, 17.1, 23.9, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (141, 8, 0, 'кетчуп', 93, 1.8, 1, 22.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (142, 10, 0, 'печенье', 400, 7.5, 11, 74);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (143, 26, 0, 'творог 9%', 159, 16, 9, 2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (144, 2, 0, 'перцы фаршированные', 154, 9.6, 10.3, 5.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (145, 24, 0, 'йогурт несладкий', 51, 2.8, 2.5, 4.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (146, 14, 0, 'перец болгарский', 27, 1.3, 0, 5.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (147, 19, 0, 'банан', 89, 1.5, 0.1, 21);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (148, 7, 0, 'пшено на воде', 88, 3, 0.9, 17);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (149, 2, 0, 'кабачки запеченые в духовке', 24, 0.6, 0.3, 4.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (150, 14, 0, 'лук репчатый', 41, 1.4, 0, 9.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (151, 14, 0, 'морковь', 32, 1.3, 0.1, 6.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (152, 7, 0, 'овсянка на воде', 92, 3, 1.7, 15);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (153, 7, 0, 'кукурузная крупа на воде', 90, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (154, 4, 0, 'скумбрия х/к', 172, 22.7, 9.6, 0.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (155, 7, 0, 'пшеничная крупа на воде', 105, 3.8, 0.4, 20.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (156, 14, 0, 'чеснок', 143, 6.5, 0.5, 29.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (157, 4, 0, 'консервы сардины', 238, 19, 18, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (158, 16, 0, 'салат столичный', 129, 6, 7, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (159, 4, 0, 'горбуша запеченая', 140, 20.4, 6.5, 2.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (161, 24, 0, 'варенец 2,5%', 50, 2.8, 2.5, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (162, 2, 0, 'капуста с грибами тушеная', 35, 1.8, 0.7, 5.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (163, 9, 0, 'колбаса домашняя свиная', 340, 15.9, 28.8, 2.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (164, 2, 0, 'овсянка на молоке', 102, 3.2, 4.1, 14.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (165, 20, 0, 'хлебцы 5 злаков', 300, 13, 2, 55);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (166, 7, 0, 'чечевица отварная', 112, 7.8, 0, 20.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (167, 18, 0, 'икра кабачковая', 97, 1.2, 7, 7.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (168, 7, 0, 'картофель жареный', 154, 2.1, 8.3, 17);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (169, 4, 0, 'консервы килька в т/с', 162, 10.5, 10, 3.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (170, 10, 0, 'печенье овсяное', 417, 6.3, 14.3, 67.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (171, 20, 0, 'баранка', 336, 16, 1, 70);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (172, 16, 0, 'салат из свеклы с майонезом', 116, 2, 8, 10.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (173, 14, 0, 'свекла отварная', 49, 1.8, 0, 10.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (174, 3, 0, 'фрикадельки', 263, 28.7, 16, 1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (175, 10, 0, 'торт 300', 290, 4, 7.5, 51);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (176, 7, 0, 'морковь с луком тушеные', 58, 1.9, 2.5, 7.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (177, 20, 0, 'хлеб для тостов', 280, 8.5, 3.5, 53);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (178, 19, 0, 'мандарины', 40, 0.8, 0.3, 8.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (179, 4, 0, 'салат из морской капусты', 74, 1, 6, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (180, 16, 0, 'салат оливье', 150, 7.7, 8.9, 7.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (181, 4, 0, 'скумбрия соленая', 194, 18, 13.1, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (182, 19, 0, 'хурма', 53, 0.5, 0, 13.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (183, 20, 0, 'булочка', 295, 7.2, 9.7, 44.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (184, 6, 0, 'сосиска в тесте', 275, 7.4, 21, 14.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (185, 4, 0, 'сельдь соленая', 198, 18.9, 14.2, 0.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (186, 3, 0, 'котлета из говядины и свинины', 230, 11.7, 16.4, 8.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (187, 2, 0, 'пшено на молоке', 103, 3.8, 5.3, 10.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (188, 7, 0, 'лук жареный', 141, 1.3, 11.5, 9.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (189, 16, 0, 'селедка под шубой', 184, 6, 14.8, 7.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (190, 16, 0, 'салат (кур.грудки...)', 79, 7, 1, 12);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (191, 10, 0, 'торт 400', 400, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (192, 13, 0, 'шампанское', 20, 0.2, 0, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (193, 4, 0, 'лаваш с красной рыбой', 190, 11.8, 10.7, 12.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (194, 5, 0, 'бутерброд с красной икрой', 350, 13.4, 21.3, 25.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (195, 13, 0, 'водка домашняя', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (196, 18, 0, 'помидоры маринованные', 18, 1.2, 0.2, 2.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (197, 18, 0, 'капуста квашеная', 19, 1.8, 0.1, 4.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (198, 18, 0, 'лечо из кабачков', 58, 0.7, 3.8, 5.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (199, 13, 0, 'вино  полусладкое', 21, 0.8, 0, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (200, 19, 0, 'гранат', 52, 0.9, 0, 11.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (201, 18, 0, 'горошек зеленый', 55, 3.6, 0.1, 9.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (202, 7, 0, 'капуста тушеная', 71, 3.8, 3.9, 12.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (203, 9, 0, 'сарделька свиная', 330, 10, 30, 1.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (204, 18, 0, 'оливки консервированные', 145, 1, 15.3, 0.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (205, 4, 0, 'икра мойвы с маслом', 451, 3, 47, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (206, 2, 0, 'манты (свинина,говядина)', 194, 6.9, 10.1, 22.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (207, 12, 1, 'соки', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (208, 207, 0, 'томатный сок', 22, 1.1, 0.2, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (209, 10, 0, 'конфеты', 370, 0.3, 0.5, 90);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (210, 32, 0, 'цикорий', 7, 0.1, 0, 2.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (211, 2, 0, 'каша 5 злаков на молоке', 105, 3.5, 1.7, 19);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (212, 16, 0, 'салат (помид,пер,лук)', 28, 1.2, 0.1, 5.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (213, 16, 0, 'салат генеральский', 154, 11.2, 10, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (214, 3, 0, 'говядина отварная', 221, 28.5, 13.9, 0.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (215, 19, 0, 'авокадо', 160, 2, 15, 9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (216, 3, 0, 'тефтели', 247, 10.7, 16.7, 13.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (217, 5, 0, 'темный бургер', 244, 12.7, 12.4, 20.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (218, 19, 0, 'апельсин', 38, 0.9, 0.2, 8.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (219, 2, 0, 'жульен с курицей и грибами', 133, 11, 8.6, 2.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (220, 4, 0, 'сельдь иваси соленая', 173, 17.5, 11.4, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (221, 18, 0, 'хренодер', 29, 1.6, 0.3, 6.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (222, 25, 0, 'сыр маасдам', 350, 23.5, 26, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (223, 20, 0, 'булочка с отрубями', 220, 7.8, 1.8, 43.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (224, 4, 0, 'кета холодного копчения', 181, 22.7, 10.1, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (225, 3, 0, 'котлета из курицы', 144, 16.2, 3.4, 12);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (226, 17, 0, 'варенье', 270, 0.6, 0.2, 70.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (227, 16, 0, 'салат с крабовыми палочками', 135, 5.1, 7.3, 11.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (228, 16, 0, 'салат из свежей капусты с маслом', 68, 1.8, 3.6, 7.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (229, 19, 0, 'ананас', 50, 0.4, 0.2, 11.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (230, 13, 0, 'пиво', 20, 0.3, 0, 4.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (231, 21, 0, 'мюсли', 330, 9.4, 3.6, 62);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (232, 19, 0, 'киви', 51, 1, 0.6, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (233, 9, 0, 'карпаччо из курицы', 162, 19.4, 8.4, 1.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (234, 19, 0, 'памело', 32, 0.6, 0.2, 6.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (235, 9, 0, 'куриная грудка варено-копченая', 132, 18.4, 6.4, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (236, 19, 0, 'айва', 49, 0.6, 0.5, 9.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (237, 24, 0, 'молоко овсяное', 40, 1, 1, 7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (238, 18, 0, 'лечо', 65, 0, 0, 16.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (239, 21, 0, 'мюсли с орехами', 400, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (240, 2, 0, 'курица с брокколи', 99, 13.4, 4, 2.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (241, 10, 0, 'халва', 523, 11.6, 29.7, 54);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (242, 16, 0, 'винегрет', 75, 1.8, 3.7, 8.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (243, 19, 0, 'малина', 46, 0.8, 0.5, 8.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (244, 6, 0, 'пирожок с творогом', 209, 9, 10, 21);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (245, 2, 0, 'курица тушеная с картофелем', 149, 8, 9.2, 9.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (246, 26, 0, 'сырок', 180, 14.3, 8, 13.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (247, 10, 0, 'вафли', 342, 3.2, 2.8, 81.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (248, 8, 0, 'соус соевый', 58, 3.5, 0, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (249, 7, 0, 'булгур отварной', 83, 3.1, 0.2, 14.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (250, 2, 0, 'курица тушеная с овощами', 95, 7, 6.9, 1.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (251, 4, 0, 'консервы иваси', 275, 17, 23, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (252, 3, 0, 'утка с яблоками и черносливом', 243, 9.6, 20.2, 4.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (253, 2, 0, 'каша гречневая на молоке', 98, 4, 3.7, 12.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (254, 18, 0, 'грузди соленые', 17, 1.2, 0.8, 1.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (255, 2, 0, 'рис на молоке', 97, 2.5, 3.1, 16);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (256, 379, 0, 'чернослив сушеный', 240, 2.2, 0.4, 64);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (257, 4, 0, 'консервы скумбрия', 206, 20, 14, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (258, 16, 0, 'салат(яблоко,селдерей,капуста,уксус)', 27, 1.2, 0.2, 5.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (259, 1, 0, 'суп гречневый с говядиной', 56, 4.3, 2.7, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (260, 4, 0, 'консервы горбуша', 140, 20, 6, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (261, 5, 0, 'ай-твистер', 235, 10.7, 11.4, 22.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (263, 9, 0, 'колбаса русская', 295, 11.1, 27.8, 0.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (264, 8, 0, 'майонез', 624, 3.1, 67, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (265, 20, 0, 'сухарики из белого хлеба', 331, 11.2, 1.4, 72.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (266, 20, 0, 'сухарики ржаные', 336, 16, 1, 70);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (267, 207, 0, 'гранатовый сок', 64, 0.3, 0, 14.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (268, 379, 0, 'имбирь в сахаре', 270, 0, 0, 78);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (269, 3, 0, 'куриные крылышки тушеные', 185, 21.3, 11, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (270, 1, 0, 'окрошка', 77, 3.8, 3.8, 7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (271, 10, 0, 'пастила хрустящая', 280, 1, 0, 71);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (272, 26, 0, 'творожок дависсимо', 154, 5.2, 7.2, 17.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (273, 20, 0, 'булочка с корицей', 241, 4.9, 6.3, 45.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (274, 25, 0, 'сыр карат шоколадный', 306, 9.2, 18, 26.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (275, 3, 0, 'курица тушеная', 163, 17.7, 9, 1.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (276, 9, 0, 'колбаса ливерная', 258, 15, 22, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (277, 6, 0, 'пирог с курицей', 230, 9.5, 11.1, 23.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (278, 10, 0, 'печенье ржано-отрубное', 422, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (279, 207, 0, 'вишневый сок', 47, 0.7, 0, 10.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (280, 4, 0, 'консервы тунец', 73, 16.3, 0.8, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (281, 24, 0, 'сметана 15%', 158, 2.6, 15, 3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (282, 10, 0, 'чокопай ', 445, 3.9, 18.3, 66.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (283, 4, 0, 'котлета из рыбы', 132, 13.9, 4.7, 9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (284, 18, 0, 'кукуруза консервированная', 58, 2.2, 0, 11.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (285, 2, 0, 'плов овощной', 115, 3.3, 4.3, 22.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (286, 9, 0, 'сало свиное', 797, 2.4, 89, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (287, 21, 0, 'кукурузные хлопья', 362, 6.9, 2.5, 83.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (288, 32, 0, 'компот из сухофруктов', 60, 0.8, 0, 14.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (289, 6, 0, 'хачапури с творогом', 229, 10.3, 5.9, 34.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (290, 7, 0, 'ржаные хлопья на воде', 81, 2.9, 0, 14.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (291, 1, 0, 'лагман со свининой', 97, 5, 7, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (292, 21, 0, 'чипсы картофельные', 520, 5.5, 30, 53);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (293, 2, 0, 'котлета морковные', 145, 2.9, 7.2, 12.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (294, 207, 0, 'апельсиновый сок', 45, 0.7, 0.2, 10);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (295, 14, 0, 'укроп', 38, 2.5, 0.5, 6.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (296, 21, 0, 'pina coloka', 440, 15.4, 2.2, 14);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (297, 3, 0, 'шашлык из свинины', 285, 20.8, 21.6, 0.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (298, 13, 0, 'вино сухое', 2, 0.2, 0, 0.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (299, 4, 0, 'печень трески', 613, 4.2, 65.7, 1.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (300, 4, 0, 'роллы', 142, 9.7, 6.7, 10.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (301, 207, 0, 'яблочный сок', 46, 0.5, 0.1, 10.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (302, 6, 0, 'пирог с картошкой', 200, 4.6, 11.5, 20.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (303, 13, 0, 'вино полусухое', 11, 0.3, 0, 2.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (304, 1, 0, 'суп солянка', 69, 5.2, 4.6, 1.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (305, 21, 0, 'мюсли белок', 109, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (306, 3, 0, 'стрипсы kfc', 219, 21.1, 10, 11.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (307, 4, 0, 'икра мойвы', 280, 12.8, 26, 2.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (308, 20, 0, 'хлеб кайзер', 215, 6.5, 2.5, 43);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (309, 4, 0, 'рыбка янтарная сушеная', 263, 57.2, 3, 2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (310, 19, 0, 'кпубника', 41, 0.8, 0.4, 7.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (311, 13, 0, 'виски', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (312, 13, 0, 'джин', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (313, 21, 0, 'пшенно-гречневые хлопья', 347, 12.5, 3.2, 66.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (314, 3, 0, 'котлета печеночноморковная', 107, 12.2, 3.8, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (315, 6, 0, 'оладьи из кабачков', 128, 3.7, 6.5, 14.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (316, 4, 0, 'скумбрия запеченая', 167, 17.1, 10.9, 0.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (317, 2, 0, 'каша гречневая с тушенкой', 167, 8.2, 9.7, 12.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (318, 1, 0, 'борщ вегетарианский', 23, 0.7, 0.8, 3.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (319, 6, 0, 'блинчики с творогом', 197, 9.6, 8.3, 20.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (320, 4, 0, 'сельдь запеченая', 164, 23.2, 7.9, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (321, 6, 0, 'пирог с яблоками легкий', 154, 3.7, 6.3, 20.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (322, 10, 0, 'панакота классическая', 147, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (323, 3, 0, 'ципленок табака', 217, 18.4, 15.4, 1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (324, 2, 0, 'пицца', 222, 4, 18, 13);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (325, 2, 0, 'шаурма куриная', 158, 7.1, 3.3, 24.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (326, 18, 0, 'капуста маринованная', 27, 1, 0.1, 5.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (327, 9, 0, 'куриные крылышки варено-копченые', 203, 20.6, 13, 0.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (328, 10, 0, 'галеты', 390, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (329, 18, 0, 'аджика домашняя', 64, 1.2, 2.8, 8.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (330, 21, 0, 'чипсы свекла', 450, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (331, 10, 0, 'батончик фруктовый глазированный', 370, 4, 6.5, 82);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (332, 4, 0, 'минтай запеченный', 81, 16.4, 1.7, 0.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (333, 10, 0, 'круоссаны', 355, 4.9, 21.3, 36.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (334, 2, 0, 'цветная капуста вкуснее мяса', 76, 3.6, 3.8, 7.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (335, 24, 0, 'молоко 2,5%', 52, 2.8, 2.5, 4.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (336, 19, 0, 'фейхоа', 49, 1.2, 0.8, 10.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (337, 379, 0, 'финики', 274, 2.5, 0.5, 69.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (338, 2, 0, 'капуста с курицей тушеные', 82, 9.8, 2.9, 4.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (339, 2, 0, 'цветная капуста в кляре', 78, 5.1, 4.8, 4.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (340, 2, 0, 'штрудель с курицей и овощами', 169, 10.9, 9.3, 10.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (341, 2, 0, 'тыква со свеклой запеченые', 50, 1.3, 2, 7.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (342, 6, 0, 'эклеры', 262, 6, 16, 24);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (343, 4, 0, 'горбуша вяленая', 162, 21, 7, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (344, 1, 0, 'щи', 56, 3.8, 3.3, 4.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (345, 16, 0, 'салат метелка', 101, 1.5, 7.3, 7.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (346, 4, 0, 'кета запеченая', 154, 25.8, 4.8, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (347, 15, 0, 'арахис', 567, 26, 49, 16);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (348, 16, 0, 'салат витаминный', 94, 1.4, 7.5, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (349, 3, 0, 'пастурма из курицы', 122, 19, 2, 1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (350, 16, 0, 'салат с фунчезой', 124, 1.2, 3.4, 23.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (351, 2, 0, 'лагман', 92, 4.3, 3, 11.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (352, 18, 0, 'шампиньоны маринованные', 26, 2.3, 0.6, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (353, 14, 0, 'капуста', 25, 1.3, 0.1, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (354, 4, 0, 'камбала жареная', 154, 14, 8.9, 4.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (355, 14, 0, 'базилик', 27, 2.5, 0.6, 4.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (356, 14, 0, 'руккола', 25, 2.6, 0.7, 2.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (357, 379, 0, 'курага', 215, 5.2, 0.3, 51);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (359, 21, 0, 'energy diet smart coffe', 300, 38.3, 5, 25);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (360, 14, 0, 'петрушка', 36, 3, 0.8, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (361, 379, 0, 'кизил вяленый', 209, 4.6, 0, 46.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (362, 9, 0, 'колбаса полукопченая', 287, 17, 23, 2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (363, 16, 0, 'салат капуста с грибами', 64, 1.6, 3.4, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (364, 26, 0, 'творог 5%', 116, 15, 5, 2.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (365, 19, 0, 'манго', 60, 0.8, 0.4, 13.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (366, 15, 0, 'орехи пекан', 690, 9, 72, 14);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (367, 5, 0, 'биг мак', 245, 12.7, 12.2, 20.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (368, 8, 0, 'горчица', 162, 5.7, 6.4, 22);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (369, 14, 0, 'капуста пекинская', 16, 1.2, 0.2, 2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (370, 6, 0, 'самса с говядиной', 165, 7.7, 3.2, 27.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (371, 2, 0, 'кус-кус на молоке', 97, 3.6, 1.2, 17.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (372, 14, 0, 'редька дайкон', 21, 1.2, 0, 4.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (373, 25, 0, 'сыр моцарелла', 240, 18, 24, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (374, 7, 0, 'горошница на воде', 89, 6, 0.7, 16.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (375, 21, 0, 'отруби ржаные', 190, 12.5, 3.1, 28);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (376, 25, 0, 'брынза', 197, 11.8, 15.5, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (377, 21, 0, 'отруби овсяные', 270, 12.2, 4.6, 46);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (379, 0, 1, 'сухофрукты, цукаты', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (380, 384, 0, 'пепси-кола', 45, 0, 0, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (381, 22, 0, 'яйцо перепелиное', 168, 11.9, 13.1, 0.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (382, 24, 0, 'сливки 10%', 118, 3, 10, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (383, 10, 0, 'батончик протеиновый', 217, 15.5, 6, 20);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (384, 12, 1, 'газированные напитки', NULL, NULL, NULL, NULL);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (385, 384, 0, 'квас', 27, 0.2, 0, 5.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (386, 379, 0, 'пастила фруктовая', 263, 2.4, 0, 59);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (387, 4, 0, 'треска жареная', 108, 17.2, 1.7, 5.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (388, 4, 0, 'тунец  на пару', 116, 23, 1.2, 0.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (389, 21, 0, 'чипсы кукурузные', 465, 9, 15, 73);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (390, 16, 0, 'салат из кабачков ', 38, 0.7, 1.4, 5.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (391, 19, 0, 'черешня', 50, 1.1, 0.4, 11.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (392, 1, 0, 'бульон мясной', 54, 7.4, 2.6, 0.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (393, 3, 0, 'котлета из курицы и кабачка', 95, 9.4, 1.7, 9.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (394, 2, 0, 'капуста белокочанная в кляре', 52, 3, 1.6, 6.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (395, 6, 0, 'оладьи', 193, 5, 4.9, 32.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (396, 15, 0, 'кешью', 553, 18, 44, 30);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (397, 4, 0, 'консервы семга', 170, 17, 10, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (398, 21, 0, 'отруби пшеничные', 290, 14, 3, 40);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (399, 9, 0, 'ветчина говядина консервы', 214, 10.2, 24.9, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (400, 2, 0, 'макароны по флотски', 232, 8.4, 14.5, 17.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (401, 19, 0, 'лимон', 29, 1.1, 0.3, 9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (402, 2, 0, 'рыжики жареные в сметане', 91, 3.2, 7.4, 3.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (403, 24, 0, 'немолоко овяное', 95, 2, 3.2, 14.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (404, 25, 0, 'сыр мягкий рикотта', 140, 8.4, 10.3, 3.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (405, 4, 0, 'консервы сельдь', 163, 16, 11, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (406, 6, 0, 'пирог с сыром и шпинатом', 189, 7.9, 7.1, 23.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (407, 6, 0, 'блинчики с мясом', 220, 9.2, 9.1, 23.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (408, 6, 0, 'сырник', 212, 15.9, 8.4, 17.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (409, 4, 0, 'шпроты', 356, 17, 32, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (410, 20, 0, 'хлеб ржаной с семечками', 296, 10.7, 16.1, 33.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (411, 20, 0, 'хлеб рижский', 227, 6.6, 1.7, 46.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (412, 19, 0, 'ананас консервированный', 69, 0.25, 0.22, 15.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (413, 19, 0, 'черноплодная рябина', 53, 1.5, 0.1, 12.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (414, 7, 0, 'пять злаков на воде', 96, 2.4, 0.4, 23.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (415, 24, 0, 'ряженка 4%', 67, 2.8, 4, 4.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (416, 379, 0, 'изюм', 264, 2.9, 0.6, 66);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (417, 10, 0, 'торт мистер пингвин', 160, 3, 5, 26);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (418, 7, 0, 'фасоль отварная', 123, 7.8, 0.5, 21.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (419, 7, 0, 'брокколи отварная', 27, 3, 0.4, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (420, 8, 0, 'подлива для котлет', 30, 1, 0.2, 6.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (421, 16, 0, 'салат(кур, свек, ябл, чернсл, май)', 138, 12.3, 5.9, 9.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (422, 9, 0, 'ветчина свинина консервы', 282, 7.5, 28, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (423, 4, 0, 'хек жареный', 147, 16.6, 9, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (424, 2, 0, 'капуста пекинская запеченая', 57, 1.3, 4.6, 2.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (425, 16, 0, 'фунчеа по корейски', 110, 0.9, 3, 19.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (426, 9, 0, 'корейка', 220, 40, 20, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (427, 16, 0, 'салат мимоза', 130, 8.3, 7.7, 7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (428, 2, 0, 'овсянка с курицей', 117, 10.1, 3.7, 10.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (429, 17, 0, 'бальзам медовая энергия', 256, 0, 0, 64);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (430, 15, 0, 'орехи макадамия', 718, 7.9, 75.8, 13.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (431, 16, 0, 'салат(редька,яблоко,морковь)', 69, 1.1, 4.3, 6.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (432, 10, 0, 'печенье овсяное дом', 200, 6, 7.6, 27.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (433, 14, 0, 'редька зеленая', 32, 2, 0.2, 6.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (434, 6, 0, 'запеканка творожная легкая', 168, 10.7, 8.3, 12.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (435, 21, 0, 'energy diet chocolat', 349, 37.8, 9, 22.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (436, 7, 0, 'кус-кус', 112, 3.8, 0.2, 21.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (437, 9, 0, 'бекон', 468, 33.9, 35.1, 1.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (438, 20, 0, 'хлеб столичный', 210, 7, 1.2, 45.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (439, 21, 0, 'овсяные хлопья', 360, 10.5, 5, 65);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (440, 21, 0, 'овсяные хлопья', 290, 11, 6, 49);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (441, 21, 0, 'energy diet cappuchino', 373, 39.7, 9.6, 27.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (442, 7, 0, 'картофель фри', 291, 3, 20, 22);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (443, 24, 0, 'йогурт даниссимо', 140, 5, 5.5, 17.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (445, 4, 0, 'консервы сардины натур', 197, 20, 13, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (446, 24, 0, 'йогурт epica', 120, 5.8, 5, 13.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (447, 10, 0, 'печенье мария', 387, 8.4, 8.6, 69);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (448, 4, 0, 'лещ холодного копчения', 160, 29.7, 4.6, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (449, 2, 0, 'вареники с картошкой и грибами', 186, 5.6, 3.7, 33.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (450, 4, 0, 'икра красная', 236, 28.3, 13.2, 1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (451, 3, 0, 'наггетсы куриные', 177, 11.9, 9.1, 12);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (452, 24, 0, 'йогурт активия', 73, 3, 2.2, 10.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (453, 24, 0, 'alpro almond', 21, 0.4, 1.1, 2.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (454, 24, 0, 'бифидок', 51, 3, 2.5, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (455, 21, 0, 'отруби бородинские', 270, 13, 2, 40);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (456, 25, 0, 'сыр гауда полутвердый', 331, 26, 25.2, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (457, 9, 0, 'грудинка свиная (домаш)', 398, 8.4, 40.5, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (458, 26, 0, 'творог из талицы', 142, 13, 4, 13.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (459, 3, 0, 'купаты свинина говядина', 252, 9.1, 23.2, 1.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (460, 2, 0, 'цветная капуста отварная', 29, 1.8, 0.3, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (461, 15, 0, 'фисташки', 569, 21.1, 45.8, 17.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (462, 14, 0, 'шпинат', 22, 2.9, 0.3, 2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (463, 10, 0, 'печенье творожное', 315, 9.2, 10.9, 44.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (464, 10, 0, 'шоколад Red Delight', 346, 8.7, 29, 34);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (465, 24, 0, 'снежок', 86, 2.8, 2.5, 13.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (466, 9, 0, 'рулет куриный', 170, 20, 10, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (467, 18, 0, 'перец острый соленый', 18, 1.3, 0, 2.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (468, 24, 0, 'ацидофилин 2,5%', 54, 3.5, 2.5, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (469, 25, 0, 'сыр тильзитер', 334, 27.8, 25, 0.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (470, 25, 0, 'сыр бри', 291, 21, 23, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (471, 3, 0, 'печень куриная тушеная', 124, 16.9, 5.5, 1.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (472, 21, 0, 'овсяные хлопья с яблоком', 347, 3.5, 4, 68);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (473, 16, 0, 'салат(мор.кап.,яйцо, майонез,кук.)', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (474, 24, 0, 'йогурт варечка', 77, 3.4, 2.5, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (475, 26, 0, 'творожок', 69, 7.9, 0.2, 9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (476, 26, 0, 'творожок виш', 112, 7, 3, 13);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (477, 384, 0, 'пепси-кола б/с', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (478, 384, 0, 'кока-кола б/с', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (479, 379, 0, 'манго вяленый', 348, 1.1, 0, 83);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (480, 4, 0, 'рыба жареная', 133, 14.3, 7.2, 2.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (481, 24, 0, 'йогурт epica б/добавок', 100, 7, 6, 4.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (482, 10, 0, 'масло шоколадное', 640, 1.5, 62, 19);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (483, 4, 0, 'кальмар копченый', 144, 32, 0.8, 2.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (484, 6, 0, 'гренки', 299, 6.9, 13.9, 33.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (485, 32, 0, 'какао', 18, 1.5, 0.6, 1.1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (486, 10, 0, 'бисквит timi', 370, 4, 12, 60);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (487, 6, 0, 'сметанник', 250, 5.4, 14.2, 24.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (488, 3, 0, 'бекон из мраморной говядины', 230, 16, 18, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (489, 21, 0, 'моментальная овс каша', 308, 9.2, 5, 56.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (490, 384, 0, 'пиво безалкогольное', 30, 0, 0, 5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (491, 25, 0, 'сыр плавленный', 295, 7.1, 28.6, 3.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (492, 14, 0, 'кинза', 23, 2.1, 0.5, 1.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (493, 21, 0, 'отруби мультизлаковые', 380, 20.2, 2.5, 67);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (494, 16, 0, 'смесь для окрошки', 94, 5.4, 5.6, 5.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (495, 24, 0, 'йогурт активия со злаками', 91, 4, 2.9, 12.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (496, 24, 0, 'йогурт ирбитский', 102, 2.9, 2.5, 17);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (497, 3, 0, 'купаты куриные', 220, 14.8, 16.5, 0.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (498, 21, 0, 'попкорн', 333, 4.5, 6.1, 65);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (499, 2, 0, 'гамбургер', 182, 7.6, 5.1, 25.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (500, 2, 0, 'пицца из кабачков', 109, 7.2, 2.7, 13.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (501, 1, 0, 'бульон нежирная свинина', 50, 3.2, 4.1, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (502, 2, 0, 'суши из курицы', 242, 9.9, 3.2, 42.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (503, 24, 0, 'биойогурт 3к2к', 105, 2.8, 6, 10);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (504, 20, 0, 'хлеб дарницкий', 206, 6.6, 1.1, 41);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (505, 9, 0, 'ветчина вязанка столичная', 102, 12, 6, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (506, 7, 0, 'пшенно-гречишные на воде', 85, 2.7, 0.7, 16.4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (507, 4, 0, 'паста с креветками', 107, 7.7, 2.9, 12.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (508, 4, 0, 'горбуша отварная', 152, 21.8, 7.3, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (509, 24, 0, 'йогурт био злаки активия', 70, 3, 1.6, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (510, 6, 0, 'чебурек', 279, 12.5, 15.6, 23.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (511, 4, 0, 'икра красная', 249, 31.5, 13.2, 1);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (512, 3, 0, 'люля-кебаб из баранины', 235, 15.8, 18.2, 0.9);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (513, 4, 0, 'мойва в духовке', 137, 10.5, 8.8, 3.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (514, 10, 0, 'печенье низкоколорийное', 178, 7.7, 2.1, 31.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (515, 18, 0, 'фасоль белая', 87, 5.3, 0.2, 16);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (516, 25, 0, 'сыр дор блю', 354, 21, 30, 2.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (517, 384, 0, 'фанта', 28, 0.1, 0, 7.2);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (518, 4, 0, 'пелядь холодного копчения', 186, 24, 10, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (519, 4, 0, 'салака х/к', 120, 17, 6, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (520, 24, 0, 'биойогурт слобода', 110, 3.6, 5, 11.7);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (521, 9, 0, 'сарделька говяжая велес', 210, 12, 18, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (522, 4, 0, 'язь х/к', 117, 19, 4.5, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (523, 6, 0, 'пончики', 296, 5.6, 13, 38.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (524, 7, 0, 'подлива', 89, 4.3, 7.3, 6.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (525, 6, 0, 'пирог с мясом', 265, 6.6, 4.3, 12.3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (526, 18, 0, 'баклажаны с овощами', 104, 2.3, 5.6, 11);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (527, 4, 0, 'консервы скумбрия д.м', 140, 13, 10, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (528, 18, 0, 'баклажаны с овощами 50к', 50, 1, 2, 6.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (529, 25, 0, 'сыр домашний', 118, 15.1, 6, 6.6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (530, 13, 0, 'бальзам рижский', 0, 0, 0, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (531, 9, 0, 'мясо индейки', 80, 12, 2, 4);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (532, 4, 0, 'пелядь вяленая', 126, 19.1, 5.5, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (533, 25, 0, 'сыр пармезан', 392, 36, 25, 3);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (534, 20, 0, 'хлеб хуторок', 240, 10.1, 3.9, 40);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (535, 25, 0, 'сыр бондарский', 351, 22.5, 29, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (536, 6, 0, 'хачапури с карицей и грибами', 270, 10, 16.3, 22.5);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (537, 20, 0, 'хлеб прованс', 261, 7.6, 0.9, 56);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (538, 5, 0, 'чикенбургер', 339, 12, 14, 37);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (539, 5, 0, 'чисбургер', 302, 16, 13, 31);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (540, 20, 0, 'хлеб ржано-пшеничный', 230, 6.5, 3.4, 45);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (541, 25, 0, 'сыр сулугуни', 279, 21.9, 21.2, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (542, 10, 0, 'чурчхела', 460, 4.9, 14.5, 78);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (543, 4, 0, 'минтай в кляре', 151, 22.4, 2.4, 10);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (544, 3, 0, 'свиная тушенка', 360, 13, 35, 0);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (545, 3, 0, 'фрикадельки на пару', 184, 15.2, 12.3, 2.8);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (546, 8, 0, 'соус сырный', 360, 2, 37, 6);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (547, 21, 0, 'berry mix ягодный микс', 333, 43.3, 8.3, 16);
INSERT INTO products (id, products_id, isgroup, name, calory, protein, fat, carbohydrate) VALUES (548, 8, 0, 'урбеч тыквенный', 529, 24.5, 45.8, 4.7);
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
